### ISSUE TITLE
[Bug]: Deleting .obsidian files doesn't work.

### ISSUE THREAD

**Issue by kadisonm** [sboesen/remotely-sync#48]
### What happened?

Somehow when I used Remotely Save it saved 8 versions of my workspace.json file, causing my ribbon to annoyingly change every time I open obsidian. I checked and these files were in my vault before I switched to Remotely Secure.

So I tried to delete it and sync. However, once the sync finishes it adds the files back from the remote provider. Not letting me delete them.

I was also having a similar issue with Remotely Save trying to delete plugins. I'd have to go onto my cloud service, delete them there first then delete them locally and sync. I can't do that now though since everything is encrypted, so I don't know what files what.

![Obsidian_OqEaAJ5HvM](https://github.com/sboesen/remotely-secure/assets/134670047/15eaf4ac-fdbc-4a24-87fd-5d3997f80bbe)

Might be related to #40.

### What OS are you using?

Windows

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.4.20

### Version of Obsidian

1.4.16

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by sboesen** [comment]
Thanks for reporting this one.

**Comment by xtpcool** [comment]
I am very grateful that someone can continue to update this plugin. Initially, I switched to Livesync due to syncing issues with the plugin. The plugin cannot delete files during syncing, and sometimes it even syncs back to an older version. This is fatal when the plugin needs to frequently update data.

**Comment by sboesen** [comment]
RE the main issue in this folder:

This occurs because of item 3 in [sync algorithm explanation](https://github.com/sboesen/remotely-sync/blob/master/docs/sync_algorithm_v2.md#sources). Deletions outside of obsidian are not tracked, which is a problem due to not being able to see the folder by default.

This might be solvable by using something similar to https://github.com/proog/obsidian-trash-explorer - and extending it to include the .obsidian folder. Otherwise I don't see a good way to solve this without keeping track of things better in a sync manifest, which has its own challenges.

**Comment by kadisonm** [comment]
> This occurs because of item 3 in sync algorithm explanation

Ah okay makes sense. I also found this happens with css snippets on remotely save, I assume it's because obsidian doesn't have a feature for deleting them, so I was doing it in the file explorer. It's not a huge deal, I ended up redoing the set up for my vault so I just deleted the duplicated files before I initially synced.

**Comment by terminar** [comment]
Just for information: same problem here in my vault with the remotely-save original, some folders and files are just multiplicated / added with some sort of counter (and some other problems mentioned in the issues list here). 

Deletion of the <name><counter> files is also ignored, i'm just somewhere understanding the plugin code and trying to isolate the problem.

I've found this fork yesterday so I'll first of all switch and then, debug any further.

**Comment by sboesen** [comment]
Yeah this is because deletion of files outside of Obsidian isn't tracked at all.

In theory we could do something like 1) scan the Vault 2) note the scan & last sync dates 3) if new scan shows files removed, delete them and sync the delete. Currently this isn't done, though, but would be happy to merge a PR for this type of behavior!

**Comment by terminar** [comment]
Even some additional "forced mark for sync deletion" in the file browser menu would make sense.
I don't understand the remotely-save code enough to do contributions but I am reading.
Holiday may be helpful ;)

(And I have to first cleanup my general plugin list because currently, Obsidian on mobile is crashing seconds after start when indexing even without sync/remotely save......)

**Comment by kadisonm** [comment]
I think we will have to store a form of the last sync dates somewhere for #43 

Could be done in it's own file or a part of this feature or metadata.

At most it would just have to be an array of objects with a boolean success and a Date object. Unless there is more information we need to convey in the sync history? We can always just drop the success part and only show each run.

**Comment by kadisonm** [comment]
Sync history data will probably have to be seperate since each last synced for this feature would be per file right? Unless the sync history data is stored per sync and then each file sync data contains an index for the sync history array pointing to a sync time?

Let me know if that makes sense. I can provide a code snippet to help visualise what I'm saying.

**Comment by sboesen** [comment]
I have to think about the structure of this more but definitely makes sense to me. I think sync history will be a different data structure based on how you described it, but this is more for the latest sync.

**Comment by sboesen** [comment]
Closing in favor of #56. Also note the current workaround is using the "Reset Sync Metadata" option in settings which should let you delete files and have that sync (to use it click the button, close obsidian, then delete files and reopen). 

![Image](https://github.com/sboesen/remotely-sync/assets/248703/90b85590-4141-43c6-83a3-f02b14351ec4)

**Comment by bytemain** [comment]
Reset sync metadata is not work for me, I reset the metadata, and reopen obsidian, it still download the files on the remote

**Comment by kadisonm** [comment]
I noticed an issue where it takes a minute or so to reset and it's easy to miss the notice for when it's done. There is also no notice saying when it starts so it seems like the button doesn't work.

You could be experiencing that. I'll look into it and fix it.

**Comment by kadisonm** [comment]
Hi @bytemain. The next update should be more clear when it starts and finishes resetting the metadata file. Please tell me if you are still having this issue when the next update comes out.
