### ISSUE TITLE
[Feature Request]: reset the remote _remotely-secure-metadata-on-remote.json file

### ISSUE THREAD

**Issue by geerteltink** [sboesen/remotely-sync#58]
### What feature are you suggesting?

I had a sync issue for some reason. 4 files and a folder where deleted on different devices (I have 3 connected via sync). I guess they are stored in this remote json file: _remotely-secure-metadata-on-remote.json.

Even though all devices where synced, the entries were still in there and showing up in the logs. I don't remember what the exact decision was, but I think it was something like ignore it. 

If we can reset the file from the settings, such issues could be solved. Obviously it should only be done after all files are synced to each device.

### What remote cloud services are you using, or suggesting adding the feature to?

OneDrive for personal

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by sboesen** [comment]
Thanks for opening this, definitely a priority due to the clear issues with syncing a vault long term (no easy way to clean this up without nuking the remote vault and re-syncing). Becomes really annoying.

**Comment by sboesen** [comment]
Sorry for the delay, thought [this](https://github.com/sboesen/remotely-sync/commit/a9c94bf52aad34f26789945f5070a29bf38b9c97) would be simpler but this should now be fixed in 0.4.31. Please reopen if the setting is not working for you.

<img width="451" alt="Screenshot 2023-12-13 at 11 45 13 PM" src="https://github.com/sboesen/remotely-sync/assets/248703/75648082-3372-4ef2-8972-2d29da5264aa">
